[profile.default]
solc-version = '0.8.22'
src = 'contracts'
out = 'out'
test = 'test/foundry'
cache_path = 'cache/foundry'
libs = [
    # We provide a set of useful contract utilities
    # in the lib directory of @layerzerolabs/toolbox-foundry:
    # 
    # - forge-std
    # - ds-test
    # - solidity-bytes-utils
    'node_modules/@layerzerolabs/toolbox-foundry/lib',
    'node_modules',
]
fs_permissions = [{ access = "read", path = "./"}]

remappings = [
    # Due to a misconfiguration of solidity-bytes-utils, an outdated version
    # of forge-std is being dragged in
    # 
    # To remedy this, we'll remap the ds-test and forge-std imports to ou own versions

    '@chainlink/contracts/=node_modules/@layerzerolabs/toolbox-foundry/lib/foundry-chainlink-toolkit/lib/chainlink-brownie-contracts/contracts/src/',
    '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
    '@openzeppelin/=lib/foundry-chainlink-toolkit/lib/openzeppelin-contracts/',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    
    
    'erc4626-tests/=lib/openzeppelin-contracts-upgradeable/lib/erc4626-tests/',
    'foundry-chainlink-toolkit/=lib/foundry-chainlink-toolkit/',
    'openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/',
    



    'ds-test/=node_modules/@layerzerolabs/toolbox-foundry/lib/ds-test',
    'forge-std/=node_modules/forge-std/',
    
    '@layerzerolabs/=node_modules/@layerzerolabs/',
    '@openzeppelin/=node_modules/@openzeppelin/',
]
